# Generated by Django 4.0 on 2021-12-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedomApp', '0002_confession_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='confession',
            field=models.TextField(max_length=2000),
        ),
    ]
