# Generated by Django 4.0 on 2021-12-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freedomApp', '0003_alter_confession_confession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=15)),
                ('comment_body', models.TextField(max_length=2000)),
                ('comment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedomApp.confession')),
            ],
        ),
    ]
